# Generated by Django 4.2 on 2025-04-19 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_dollaraccount_dollar_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='kyc',
            name='face_encoding',
            field=models.TextField(blank=True, null=True),
        ),
    ]
