# Generated by Django 4.2 on 2025-04-19 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='face_verification_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='verification_method',
            field=models.CharField(choices=[('PIN', 'PIN'), ('FACE', 'Face Recognition')], default='PIN', max_length=10),
        ),
    ]
