# Generated by Django 4.2 on 2025-04-19 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_transaction_face_verification_status_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'status'], name='core_transa_user_id_5b29f4_idx'),
        ),
    ]
